package ai.deepseek.dshmobile.data

import android.content.Context
import androidx.core.content.edit

/**
 * Persistent settings.
 *
 * The app has two independent back ends:
 *  - REMOTE: talk to a DeepSeek Harness instance over its HTTP/WebSocket API.
 *  - API:    talk straight to an OpenAI-compatible chat-completions endpoint.
 */
enum class Backend { REMOTE, API }

data class ServerProfile(
    val name: String,
    val baseUrl: String,
    val token: String = "",
) {
    /** Normalised origin, always without a trailing slash. */
    val origin: String get() = baseUrl.trim().trimEnd('/')
}

data class ApiConfig(
    val baseUrl: String = "https://api.deepseek.com",
    val apiKey: String = "",
    val model: String = "deepseek-chat",
    val systemPrompt: String = "",
)

class Prefs(context: Context) {

    private val sp = context.getSharedPreferences("dsh_mobile", Context.MODE_PRIVATE)

    var backend: Backend
        get() = runCatching { Backend.valueOf(sp.getString(KEY_BACKEND, Backend.REMOTE.name)!!) }
            .getOrDefault(Backend.REMOTE)
        set(v) = sp.edit { putString(KEY_BACKEND, v.name) }

    // ---- remote server -----------------------------------------------------

    var serverUrl: String
        get() = sp.getString(KEY_SERVER_URL, "") ?: ""
        set(v) = sp.edit { putString(KEY_SERVER_URL, v.trim()) }

    /**
     * The browser session cookie issued by the Harness. Obtained automatically
     * from the `?token=` handshake; kept so the user does not have to re-pair.
     */
    var sessionCookie: String
        get() = sp.getString(KEY_COOKIE, "") ?: ""
        set(v) = sp.edit { putString(KEY_COOKIE, v) }

    var serverName: String
        get() = sp.getString(KEY_SERVER_NAME, "") ?: ""
        set(v) = sp.edit { putString(KEY_SERVER_NAME, v) }

    /**
     * Device token issued by the `dsh-connect` plugin on the desktop.
     *
     * When this is set the app talks to the plugin's LAN gateway instead of the
     * Harness directly. That is the supported path: the gateway holds the
     * Harness session and the phone only ever carries this token, so there is
     * no port forwarding and no cookie to manage.
     */
    var deviceToken: String
        get() = sp.getString(KEY_DEVICE_TOKEN, "") ?: ""
        set(v) = sp.edit { putString(KEY_DEVICE_TOKEN, v.trim()) }

    /** True when the app should use the gateway path. */
    val usesGateway: Boolean get() = deviceToken.isNotBlank() && serverUrl.isNotBlank()

    // ---- direct API --------------------------------------------------------

    var apiBaseUrl: String
        get() = sp.getString(KEY_API_URL, "https://api.deepseek.com") ?: "https://api.deepseek.com"
        set(v) = sp.edit { putString(KEY_API_URL, v.trim()) }

    var apiKey: String
        get() = sp.getString(KEY_API_KEY, "") ?: ""
        set(v) = sp.edit { putString(KEY_API_KEY, v.trim()) }

    var apiModel: String
        get() = sp.getString(KEY_API_MODEL, "deepseek-chat") ?: "deepseek-chat"
        set(v) = sp.edit { putString(KEY_API_MODEL, v.trim()) }

    var apiSystemPrompt: String
        get() = sp.getString(KEY_API_SYSTEM, "") ?: ""
        set(v) = sp.edit { putString(KEY_API_SYSTEM, v.trim()) }

    // ---- update ------------------------------------------------------------

    var updateManifestUrl: String
        get() = sp.getString(KEY_UPDATE_URL, DEFAULT_UPDATE_URL) ?: DEFAULT_UPDATE_URL
        set(v) = sp.edit { putString(KEY_UPDATE_URL, v.trim()) }

    var lastUpdateCheck: Long
        get() = sp.getLong(KEY_LAST_UPDATE, 0L)
        set(v) = sp.edit { putLong(KEY_LAST_UPDATE, v) }

    /** Set once the user has been told about a given version, so we do not nag. */
    var skippedVersion: String
        get() = sp.getString(KEY_SKIPPED_VERSION, "") ?: ""
        set(v) = sp.edit { putString(KEY_SKIPPED_VERSION, v) }

    private companion object {
        const val KEY_BACKEND = "backend"
        const val KEY_SERVER_URL = "server_url"
        const val KEY_SERVER_NAME = "server_name"
        const val KEY_COOKIE = "session_cookie"
        const val KEY_DEVICE_TOKEN = "device_token"
        const val KEY_API_URL = "api_url"
        const val KEY_API_KEY = "api_key"
        const val KEY_API_MODEL = "api_model"
        const val KEY_API_SYSTEM = "api_system"
        const val KEY_UPDATE_URL = "update_manifest_url"
        const val KEY_LAST_UPDATE = "last_update_check"
        const val KEY_SKIPPED_VERSION = "skipped_version"

        /**
         * Where the app looks for a newer build.
         *
         * This resolves to the newest non-prerelease GitHub Release, whose
         * `update.json` asset is generated by `.github/workflows/release.yml`.
         * Because the URL tracks "latest", publishing a release is all it takes
         * for every installed app to see it — no code change, no re-point.
         *
         * Users can override it in Settings if they host their own manifest.
         */
        const val DEFAULT_UPDATE_URL =
            "https://github.com/nmaych/dsh-mobile/releases/latest/download/update.json"
    }
}
